"""
Single-rebar geometry inversion pipeline.

This is the clean starting point for systematic development: synthesize data
from one circular rebar, then recover its lateral position, depth, and radius.
The unknown vector is [x_center, z_center, radius] in meters.
"""
from dataclasses import dataclass
import time as timer

import numpy as np
from scipy.optimize import Bounds, minimize

import config as cfg
from core.fdtd import FDTDSimulator
from core.geometry import build_single_rebar_model
from core.materials import MaterialModel
from core.source import generate_time_array, ricker_wavelet
from core.utils import pos_to_index
from inversion.adjoint import _build_mute_window
from inversion.objective import compute_normalized_rms


@dataclass(frozen=True)
class SingleRebarParams:
    """Physical parameters for a circular rebar cross-section."""

    x: float
    z: float
    radius: float

    def as_array(self):
        return np.array([self.x, self.z, self.radius], dtype=np.float64)

    @classmethod
    def from_array(cls, values):
        values = np.asarray(values, dtype=np.float64)
        return cls(float(values[0]), float(values[1]), float(values[2]))

    def as_mm(self):
        return {
            "x_mm": self.x * 1000.0,
            "z_mm": self.z * 1000.0,
            "radius_mm": self.radius * 1000.0,
        }


def default_single_rebar_truth():
    """Default one-rebar scenario: centered #4-like bar at 50 mm cover."""
    return SingleRebarParams(
        x=0.5 * cfg.DOMAIN_X,
        z=cfg.CONCRETE_TOP + cfg.REBAR_COVER,
        radius=cfg.REBAR_RADIUS,
    )


def default_single_rebar_initial_guess():
    """Deliberately imperfect but plausible starting guess."""
    return SingleRebarParams(
        x=0.5 * cfg.DOMAIN_X - 0.015,
        z=cfg.CONCRETE_TOP + cfg.REBAR_COVER - 0.010,
        radius=cfg.REBAR_RADIUS + 0.002,
    )


def _cupy_device_available():
    try:
        import cupy as cp

        return cp.cuda.runtime.getDeviceCount() > 0
    except Exception:
        return False


def _resolve_backend(backend):
    if backend == "auto":
        return "gpu-cpml" if _cupy_device_available() else "cpu"
    if backend not in ("cpu", "gpu-cpml"):
        raise ValueError(f"Unsupported backend: {backend}")
    return backend


def _build_scan_positions(scan_step, n_sources):
    scan_x_all = np.arange(cfg.SCAN_START_X, cfg.SCAN_END_X + 1e-10, scan_step)
    if n_sources is not None and n_sources < len(scan_x_all):
        idx = np.linspace(0, len(scan_x_all) - 1, n_sources, dtype=int)
        idx = np.unique(idx)
        scan_x = scan_x_all[idx]
    else:
        scan_x = scan_x_all

    src_iz = pos_to_index(cfg.TX_Z, cfg.DZ, cfg.NPML)
    rec_iz = pos_to_index(cfg.RX_Z, cfg.DZ, cfg.NPML)

    positions = []
    for x_pos in scan_x:
        src_ix = pos_to_index(x_pos, cfg.DX, cfg.NPML)
        rec_ix = pos_to_index(x_pos + cfg.TX_RX_OFFSET, cfg.DX, cfg.NPML)
        rec_ix = min(rec_ix, cfg.NX - cfg.NPML - 1)
        positions.append((src_iz, src_ix, rec_iz, rec_ix))
    return positions, scan_x


def build_model_from_single_params(params):
    params = SingleRebarParams.from_array(params)
    return build_single_rebar_model(params.x, params.z, params.radius)


class SingleRebarInversionEngine:
    """
    Recover one circular rebar from synthetic GPR data.

    The objective compares muted B-scans generated by candidate geometry
    parameters against synthetic observations from a known one-rebar model.
    """

    def __init__(
            self,
            true_params=None,
            initial_params=None,
            frequencies=None,
            n_sources=9,
            scan_step=None,
            backend="cpu",
            log_every=5):
        self.true_params = true_params or default_single_rebar_truth()
        self.initial_params = initial_params or default_single_rebar_initial_guess()
        self.frequencies = tuple(frequencies or (cfg.F_CENTER,))
        self.scan_step = scan_step or cfg.INVERSION_SCAN_STEP
        self.backend = _resolve_backend(backend)
        self.log_every = log_every

        self.scan_positions, self.scan_x = _build_scan_positions(
            self.scan_step, n_sources
        )
        self.time = generate_time_array(cfg.NT, cfg.DT)
        self.mute = _build_mute_window(cfg.NT, cfg.DT)
        self.eval_count = 0
        self.misfit_history = []

        print("Building one-rebar observed data set...")
        print(f"  True: {self.true_params.as_mm()}")
        print(f"  Initial: {self.initial_params.as_mm()}")
        print(f"  Sources: {len(self.scan_positions)}")
        print(f"  Frequencies GHz: {[f / 1e9 for f in self.frequencies]}")
        print(f"  Backend: {self.backend}")

        self.true_model = build_single_rebar_model(
            self.true_params.x,
            self.true_params.z,
            self.true_params.radius,
        )
        self.initial_model = build_single_rebar_model(
            self.initial_params.x,
            self.initial_params.z,
            self.initial_params.radius,
        )

        self.wavelets = {
            f: ricker_wavelet(self.time, f)
            for f in self.frequencies
        }
        self.d_obs_by_frequency = {
            f: self._simulate_bscan(self.true_model, self.wavelets[f])
            for f in self.frequencies
        }
        self.obs_norm_by_frequency = {
            f: max(
                0.5 * np.sum((self.d_obs_by_frequency[f] * self.mute[:, None]) ** 2),
                1e-30,
            )
            for f in self.frequencies
        }

    def parameter_bounds(self):
        """Return physical bounds for [x, z, radius]."""
        lower = np.array([
            cfg.SCAN_START_X,
            cfg.CONCRETE_TOP + 0.010,
            0.003,
        ])
        upper = np.array([
            cfg.SCAN_END_X,
            min(cfg.DOMAIN_Z - 0.020, cfg.CONCRETE_TOP + 0.160),
            0.015,
        ])
        return Bounds(lower, upper)

    def _params_inside_model(self, params):
        x, z, radius = SingleRebarParams.from_array(params).as_array()
        return (
            x - radius > 0.0
            and x + radius < cfg.DOMAIN_X
            and z - radius > cfg.CONCRETE_TOP
            and z + radius < cfg.DOMAIN_Z
        )

    def _make_simulator(self, model):
        if self.backend == "cpu":
            return FDTDSimulator(model)

        from gpu.fdtd_gpu_v2 import FDTDSimulatorGPU_v2

        return FDTDSimulatorGPU_v2(model, cfg)

    def _simulate_bscan(self, model, wavelet):
        bscan = np.zeros((cfg.NT, len(self.scan_positions)), dtype=np.float64)
        sim = self._make_simulator(model)

        for i, (src_iz, src_ix, rec_iz, rec_ix) in enumerate(self.scan_positions):
            result = sim.run(wavelet, src_iz, src_ix, rec_iz, rec_ix)
            bscan[:, i] = result["trace"]

        return bscan

    def objective(self, values):
        values = np.asarray(values, dtype=np.float64)
        self.eval_count += 1

        if not self._params_inside_model(values):
            return 1.0e6

        model = build_model_from_single_params(values)

        total = 0.0
        for f in self.frequencies:
            d_syn = self._simulate_bscan(model, self.wavelets[f])
            residual = (d_syn - self.d_obs_by_frequency[f]) * self.mute[:, None]
            total += 0.5 * np.sum(residual ** 2) / self.obs_norm_by_frequency[f]

        misfit = total / len(self.frequencies)
        self.misfit_history.append(misfit)

        if self.eval_count <= 3 or self.eval_count % self.log_every == 0:
            params = SingleRebarParams.from_array(values)
            print(
                f"  Eval {self.eval_count}: J={misfit:.6e}, "
                f"x={params.x * 1000:.1f} mm, "
                f"z={params.z * 1000:.1f} mm, "
                f"r={params.radius * 1000:.1f} mm"
            )

        return misfit

    def run(self, max_iter=20, max_evals=None):
        bounds = self.parameter_bounds()
        x0 = self.initial_params.as_array()
        max_evals = max_evals or max(30, max_iter * 12)

        print("\nStarting one-rebar geometry inversion...")
        print(f"  Max iterations: {max_iter}")
        print(f"  Max evaluations: {max_evals}")

        t_start = timer.time()
        opt_result = minimize(
            self.objective,
            x0,
            method="Powell",
            bounds=bounds,
            options={
                "maxiter": max_iter,
                "maxfev": max_evals,
                "xtol": cfg.DX / 2.0,
                "ftol": 1e-5,
                "disp": True,
            },
        )
        elapsed = timer.time() - t_start

        optimal_params = SingleRebarParams.from_array(opt_result.x)
        inverted_model = build_single_rebar_model(
            optimal_params.x,
            optimal_params.z,
            optimal_params.radius,
        )

        d_syn_final_by_frequency = {
            f: self._simulate_bscan(inverted_model, self.wavelets[f])
            for f in self.frequencies
        }

        nrms_data_by_frequency = {
            f: compute_normalized_rms(
                self.d_obs_by_frequency[f],
                d_syn_final_by_frequency[f],
            )
            for f in self.frequencies
        }
        n = cfg.NPML
        nrms_model = compute_normalized_rms(
            self.true_model.epsilon_r[n:-n, n:-n],
            inverted_model.epsilon_r[n:-n, n:-n],
        )

        print("\nOne-rebar inversion complete.")
        print(f"  Runtime: {elapsed:.1f} s")
        print(f"  Evaluations: {self.eval_count}")
        print(f"  Success: {opt_result.success} ({opt_result.message})")
        print(f"  Recovered: {optimal_params.as_mm()}")
        print(f"  True:      {self.true_params.as_mm()}")
        print(f"  NRMS model: {nrms_model:.4f}")

        primary_frequency = self.frequencies[0]
        return {
            "initial_epsr": self.initial_model.epsilon_r,
            "inverted_epsr": inverted_model.epsilon_r,
            "true_epsr": self.true_model.epsilon_r,
            "d_obs": self.d_obs_by_frequency[primary_frequency],
            "d_syn_final": d_syn_final_by_frequency[primary_frequency],
            "d_obs_by_frequency": self.d_obs_by_frequency,
            "d_syn_final_by_frequency": d_syn_final_by_frequency,
            "scan_x": self.scan_x,
            "time": self.time,
            "misfit_history": np.array(self.misfit_history),
            "initial_params": self.initial_params.as_array(),
            "optimal_params": optimal_params.as_array(),
            "true_params": self.true_params.as_array(),
            "frequencies": np.array(self.frequencies),
            "nrms_data_by_frequency": nrms_data_by_frequency,
            "nrms_model": nrms_model,
            "elapsed_time": elapsed,
            "optimizer_success": bool(opt_result.success),
            "optimizer_message": str(opt_result.message),
        }
